// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/dashboard/impact-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/impact-settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/impact-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/product-impact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/product-impact">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/product-impact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/regulations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/regulations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/regulations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/staff-users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff-users">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/staff-users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/newsletter-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/newsletter-preview">> = Specific
  const handler = {} as typeof import("../../src/app/newsletter-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../src/app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/staff-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/staff-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/staff-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/staff-signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/staff-signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/staff-signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/impact-keywords/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/impact-keywords">> = Specific
  const handler = {} as typeof import("../../src/app/api/impact-keywords/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/latest-verified-updates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/latest-verified-updates">> = Specific
  const handler = {} as typeof import("../../src/app/api/latest-verified-updates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/regulations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/regulations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/regulations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/regulations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/regulations">> = Specific
  const handler = {} as typeof import("../../src/app/api/regulations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/run-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/run-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/send-newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/api/send-newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sharepoint/product-impact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sharepoint/product-impact">> = Specific
  const handler = {} as typeof import("../../src/app/api/sharepoint/product-impact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/staff-users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff-users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/staff-users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/staff-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff-users">> = Specific
  const handler = {} as typeof import("../../src/app/api/staff-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verified-updates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verified-updates">> = Specific
  const handler = {} as typeof import("../../src/app/api/verified-updates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
